In [1]:
import numpy as np

In [2]:
a = np.array([[1, 4, 7], [3, 5, 9], [-1, 7, -2], [1, 4, 8]], float)
print(a)

[[ 1.  4.  7.]
 [ 3.  5.  9.]
 [-1.  7. -2.]
 [ 1.  4.  8.]]


In [3]:
b = a * 2
print(b)

[[ 2.  8. 14.]
 [ 6. 10. 18.]
 [-2. 14. -4.]
 [ 2.  8. 16.]]


In [4]:
c = a + 1
print(c)

[[ 2.  5.  8.]
 [ 4.  6. 10.]
 [ 0.  8. -1.]
 [ 2.  5.  9.]]


In [5]:
d = np.add(c, b)
print(d)

[[ 4. 13. 22.]
 [10. 16. 28.]
 [-2. 22. -5.]
 [ 4. 13. 25.]]


In [6]:
d = np.subtract(b, c)
print(d)

[[ 0.  3.  6.]
 [ 2.  4.  8.]
 [-2.  6. -3.]
 [ 0.  3.  7.]]


In [7]:
f = d.transpose()
print(d)
print("")
print(f)

[[ 0.  3.  6.]
 [ 2.  4.  8.]
 [-2.  6. -3.]
 [ 0.  3.  7.]]

[[ 0.  2. -2.  0.]
 [ 3.  4.  6.  3.]
 [ 6.  8. -3.  7.]]


In [8]:
i, j = 0, 0
d[i, 0] * f[0, j] + d[i, 3] * f[3, j] + d[i, 6] * f[6, j]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [9]:
g = np.dot(d, f)
print(g)
d.shape, f.shape

[[45. 60.  0. 51.]
 [60. 84. -4. 68.]
 [ 0. -4. 49. -3.]
 [51. 68. -3. 58.]]


((4, 3), (3, 4))