In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.array([[1, 2, 1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])
np.linalg.lstsq(A, B)

<ipython-input-2-990b50e0463e>:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(A, B)


(array([ 1.22624108, -0.71604718, -0.69545345]),
 array([5.21202515]),
 3,
 array([15.2235428 ,  9.45710672,  4.21981957]))