In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 0 6]
 [7 8 9]]


In [3]:
np.linalg.det(a)

59.999999999999986

In [5]:
1 * (0 * 9 - 6 * 8) - 2 * (4 * 9 - 6 * 7) + 3 * (4 * 8 - 0 * 7)

60