In [1]:
import numpy as np

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [4]:
a1 = a.reshape(2, 6)
a2 = a.reshape(3, 4)
a3 = a.reshape(4, 3)
a4 = a.reshape(6, 2)
a5 = a.reshape(12, 1)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [5]:
a1 = a.reshape(2, -1)
a2 = a.reshape(3, -1)
a3 = a.reshape(-1, 2)
a4 = a.reshape(-1, 3)
a5 = a.reshape(12, -1)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [6]:
#Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Нет, массив Numpy, состоящий из 12 строк и одного столбца, имеет номер строки и номер столбца, а также
выводится как двумерный массив с дополнительными квадратными скобками

In [7]:
b = np.random.randn(3, 4)
b

array([[-0.30218986,  0.111781  , -0.10780172, -2.66653694],
       [ 1.05701073, -0.47082676,  0.14502351, -0.37762058],
       [ 0.75744245, -0.51707024,  0.26299781,  1.63460462]])

In [8]:
print(b.size)
b = b.flatten()
print(b.size)
b

12
12


array([-0.30218986,  0.111781  , -0.10780172, -2.66653694,  1.05701073,
       -0.47082676,  0.14502351, -0.37762058,  0.75744245, -0.51707024,
        0.26299781,  1.63460462])

In [9]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [10]:
b = np.arange(20, 1, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, 
чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, 
равный 10:


In [11]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [12]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
v.size

10

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. 
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 
3 столбцов. 
Получить матрицу At путем транспонирования матрицы A. 
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. 
Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?:

In [15]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [18]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [19]:
B.size

16

In [20]:
B.shape

(4, 4)

In [21]:
# Вычислить не получится, так как это вырожденная (сингулярная) матрица
B_inv=np.linalg.inv(B)
B_inv

LinAlgError: Singular matrix

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42:

In [22]:
np.random.seed(42)

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно 
распределенных целых чисел от 0 до 16 невключительно: 


In [23]:
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

Поменяйте его форму так, чтобы получилась квадратная матрица C. 
Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. 
Вычислите определитель, ранг и обратную матрицу D_inv для D:


In [24]:
C = c.reshape(4, 4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [25]:
D = B + C * 10
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [26]:
np.linalg.det(D)

-28511999.999999944

In [27]:
np.linalg.matrix_rank(D)

4

In [28]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. 
Убедитесь, что в матрице D_inv остались только нули и единицы: 


In [29]:
D_inv = np.where(D_inv < 0, 0, 1)
D_inv

array([[1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 0]])

С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве 
источников данных, получите матрицу E размером 4x4.  
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, 
должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, 
для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему 
элементу матрицы C.


In [30]:
print(B)
print(C)
E = np.where(D_inv == 1, B, C)
E

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])