In [1]:
import numpy as np

In [2]:
# 2. Найдите сумму и произведение матриц  𝐴 и 𝐵.
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица С = A + B\n{A + B}')
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Матрица С = A + B
[[ 5 -3]
 [ 3  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]


In [3]:
# 1. Установите, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найдите размерности полученных матриц:

# а)  𝐴  — матрица  4×2 ,  𝐵  — матрица  4×2 

A = np.array([[1, -2], [3, 0], [4, 9], [0, 2]])
B = np.array([[4, -1], [0, 5], [2, -3], [0, 7]])
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица A
[[ 1 -2]
 [ 3  0]
 [ 4  9]
 [ 0  2]]
Матрица B
[[ 4 -1]
 [ 0  5]
 [ 2 -3]
 [ 0  7]]


ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

#### Такие матрицы нельзя перемножить, число столбцов матрицы А не равно числу строк матрицы В

In [4]:
# б)  𝐴  — матрица  2×5 ,  𝐵  — матрица  5×3;

A = np.array([[1, -2, 3, 0, 9], [4, 9, 0, 2, 5]])
B = np.array([[4, -1, 3], [0, 5, 2], [0, 7, 0], [2, -1, 0], [2, 8, 4]])
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица A
[[ 1 -2  3  0  9]
 [ 4  9  0  2  5]]
Матрица B
[[ 4 -1  3]
 [ 0  5  2]
 [ 0  7  0]
 [ 2 -1  0]
 [ 2  8  4]]
Матрица AB
[[22 82 35]
 [30 79 50]]


In [5]:
AB = np.array([[22, 82, 35], [30, 79, 50]]) # узнаем размерность полученной матрицы
AB.shape

(2, 3)

In [6]:
# в)  𝐴  — матрица  8×3 ,  𝐵  — матрица  3×8;

A = np.array([[1, -2, 3], [4, 9, 0], [1, 2, 3], [4, 5, 6], [7, 8, 9], [-1, -2, -3], [0, 0, 1], [0, 4, 6]])
B = np.array([[4, -1, 3, 0, 5, 2, 5, 6], [0, 7, 0, 2, -1, 0, 5, 3], [2, 8, 4, 0, 0, 4, 5, 6]])
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица A
[[ 1 -2  3]
 [ 4  9  0]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [-1 -2 -3]
 [ 0  0  1]
 [ 0  4  6]]
Матрица B
[[ 4 -1  3  0  5  2  5  6]
 [ 0  7  0  2 -1  0  5  3]
 [ 2  8  4  0  0  4  5  6]]
Матрица AB
[[ 10   9  15  -4   7  14  10  18]
 [ 16  59  12  18  11   8  65  51]
 [ 10  37  15   4   3  14  30  30]
 [ 28  79  36  10  15  32  75  75]
 [ 46 121  57  16  27  50 120 120]
 [-10 -37 -15  -4  -3 -14 -30 -30]
 [  2   8   4   0   0   4   5   6]
 [ 12  76  24   8  -4  24  50  48]]


#### Размерность матрицы 8x8

In [7]:
# г)  𝐴  — квадратная матрица  4×4 ,  𝐵  — квадратная матрица  4×4

A = np.array([[1, -2, 3, -1], [4, 9, 0, 2], [1, 2, 3, 4], [4, 5, 6, 0]])
B = np.array([[4, -1, 3, 0], [0, 7, 0, 2], [2, 8, 4, 0], [1, -2, 3, 0]])
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица A
[[ 1 -2  3 -1]
 [ 4  9  0  2]
 [ 1  2  3  4]
 [ 4  5  6  0]]
Матрица B
[[ 4 -1  3  0]
 [ 0  7  0  2]
 [ 2  8  4  0]
 [ 1 -2  3  0]]
Матрица AB
[[ 9 11 12 -4]
 [18 55 18 18]
 [14 29 27  4]
 [28 79 36 10]]


#### Размерность матрицы 4x4

In [8]:
# 4. Вычислите  𝐴*𝐴^𝑇  и  𝐴^𝑇*𝐴 

A = np.array([[4, 1], [5, -2], [2, 3]])
print(f'Матрица A\n{A}')

Матрица A
[[ 4  1]
 [ 5 -2]
 [ 2  3]]


In [9]:
print(f'Транспонированная матрица:C\n{A.T}')

Транспонированная матрица:C
[[ 4  5  2]
 [ 1 -2  3]]


In [10]:
C = np.array([[4, 5, 2], [1, -2, 3]])
print(f'Матрица AC\n{np.dot(A, C)}') # 𝐴*𝐴^𝑇

Матрица AC
[[17 18 11]
 [18 29  4]
 [11  4 13]]


In [11]:
print(f'Матрица CA\n{np.dot(C, A)}') # 𝐴^𝑇*𝐴

Матрица CA
[[45  0]
 [ 0 14]]


In [12]:
# 5. Напишите на Python функцию для перемножения двух произвольных матриц, не используя NumPy

# На примере квадратной матрицы:

a = [[1, 1, 0],
     [1, 0, 2],
     [2, 3, 4]]
     
b = [[1, 0, 2],
     [2, 1, 2],
     [1, 1, 0]]

m = len(a)                                            # a: m × n
n = len(b)                                            # b: n × k
k = len(b[0])

c = [[None for __ in range(k)] for __ in range(m)]    # c: m × k

for i in range(m):
    for j in range(k):       
        c[i][j] = sum(a[i][kk] * b[kk][j] for kk in range(n))
  
print(c)

[[3, 1, 4], [3, 2, 2], [12, 7, 10]]


In [13]:
# На примере матриц разной размерности:

a = [[1, 1, 0],
     [1, 0, 2]]
     
b = [[1, 0, 2, 1],
     [2, 1, 2, 0],
     [1, 1, 0, 3]]

m = len(a)                                            # a: m × n
n = len(b)                                            # b: n × k
k = len(b[0])

c = [[None for __ in range(k)] for __ in range(m)]    # c: m × k

for i in range(m):
    for j in range(k):       
        c[i][j] = sum(a[i][kk] * b[kk][j] for kk in range(n))
  
print(c)

[[3, 1, 4, 1], [3, 2, 2, 7]]


## Практическое задание / часть №2

In [14]:
# 1. Вычислите определитель

a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180


In [15]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
-0


In [16]:
#  3. Докажите, что матрица вырожденная

a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


#### Матрица вырожденная, так как определеить равен 0.

In [17]:
# 4. Найдите ранг матрицы

x = [1, 2, 3]
y = [1, 1, 1]
z = [2, 3, 4]

a = np.array([x, y, z])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


In [18]:
x = [0, 0, 2, 1]
y = [0, 0, 2, 2]
z = [0, 0, 4, 3]
w = [2, 3, 5, 6]

a = np.array([x, y, z, w])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
