In [1]:
# Найnb посредством NumPy SVD для матрицы
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [2]:
A = np.array([[1, 2, 3],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  3]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [3]:
U, s, W = np.linalg.svd(A)

# Транспонируем матрицу W
V = W.T

D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [4]:
print(f'Матрица D:\n{D}')

Матрица D:
[[9.43 0.   0.  ]
 [0.   6.11 0.  ]
 [0.   0.   2.16]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [5]:
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.39 -0.11 -0.18 -0.88 -0.15]
 [ 0.4  -0.46  0.78  0.05  0.13]
 [-0.08 -0.85 -0.48  0.16  0.07]
 [ 0.82  0.18 -0.33  0.42 -0.07]
 [ 0.07  0.12 -0.12 -0.12  0.98]]


In [6]:
# Убедимся, что она действительно ортогональна
print(np.dot(U.T, U))

[[ 1. -0.  0.  0.  0.]
 [-0.  1. -0. -0. -0.]
 [ 0. -0.  1. -0. -0.]
 [ 0. -0. -0.  1. -0.]
 [ 0. -0. -0. -0.  1.]]


In [7]:
print(f'Матрица V:\n{V}')

Матрица V:
[[ 0.1  -0.41 -0.91]
 [ 0.65  0.72 -0.25]
 [ 0.75 -0.56  0.34]]


In [8]:
# Убедимся, что она действительно ортогональна
print(np.dot(V.T, V))

[[ 1.  0. -0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]


In [9]:
# Проведем проверку
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2.  3.]
 [ 0.  0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [ 0.  1. -0.]]


In [10]:
# Для матрицы а) евклидову норму;
from numpy.linalg import norm

In [11]:
A = np.array([[1, 2, 3],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  3]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [12]:
norm_l2 = norm(A)
print(norm_l2)

11.445523142259598


In [13]:
from numpy import linalg as LA

In [14]:
A = np.array([[1, 2, 3],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  3]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [15]:
LA.norm(A, 'fro')

11.445523142259598