#### 1. Найдите собственные векторы и собственные значения для линейного оператора, заданного матрицей:

In [1]:
import numpy as np

np.set_printoptions(precision=2, suppress=True)

In [2]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]]


#### 2. Дан оператор поворота на 180 градусов, задаваемый матрицей. Покажите, 
#### что любой вектор считается для него собственным.

In [3]:
a = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


#### Любой вектор считается для него собственным.